// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef tmaster_h
#define tmaster_h
#include <FL/Fl.H>
const int Get_NextAction(int s);
void Reset();
void Window_Callback(Fl_Widget*, void*);
void Widget_Callback(Fl_Widget*, void*);
void Timeout_Callback(Fl_Widget*, void*);
#include <FL/Fl_Window.H>
extern Fl_Window *main_Window;
#include <FL/Fl_Progress.H>
extern Fl_Progress *ticker;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_CurrStatus;
#include <FL/Fl_Box.H>
extern Fl_Box *lbl_Remaining;
void make_window();
#endif
